project_id = "uaqokyxsvzmslndqtovk"

[functions.process-article-ai]
verify_jwt = false

[functions.send-newsletter-email]
verify_jwt = false

[functions.fetch-rss]
verify_jwt = false

[functions.process-articles]
verify_jwt = false

[functions.daily-news-pipeline]
verify_jwt = false

[functions.fetch-crime-data]
verify_jwt = false

[functions.fetch-weather]
verify_jwt = false

[functions.import-businesses]
verify_jwt = false

[functions.import-rss-articles]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false